language: java
jobs:
  include:
    - name: "Java 11"
      jdk: openjdk11

script:
 - mvn clean compile
 - mvn test
 - mvn datanucleus:enhance
 - mvn datanucleus:schema-create

branches:
  only:
  - master

notifications:
  email:
    recipients:
      - inigonavarro@opendeusto.es
      
    on_success: always
    on_failure: always

after_success:
    