language: java
jobs:
  include:
    - name: "Java 11"
      jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

script:
 - mvn clean compile
 - mvn test
 - mvn datanucleus:enhance
 - mvn datanucleus:schema-create

branches:
  only:
  - master

notifications:
  email:
    recipients:
      - inigonavarro@opendeusto.es
      
    on_success: always
    on_failure: always

after_success:
 # - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn clean test jacoco:report coveralls:report
    