
jobs:
  include:
    - name: "Java 11"
      jdk: openjdk11
      
cache:
  directories:
    - $HOME/.m2

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn clean test jacoco:report coveralls:report