language: java
jobs:
  include:
    - name: "Java 11"
      jdk: openjdk11

script:
 - mvn clean compile
 - mvn test
 - mvn datanucleus:enhance
 - mvn datanucleus:schema-create

branches:
  only:
  - master



after_success:
    bash <(curl -s https://codecov.io/bash)