language: java

jdk: 
 - openjdk11
      
script:
 - mvn clean compile
 - mvn test

branches:
	only:
		-master
		
notifications:
  email:
    recipients:
    	- ing@amigosdelwindsurf.es
    	
    	on_success: always
    	on_failure: always
    
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn clean test jacoco:report coveralls:report